services:
  - type: web
    name: empire-game
    runtime: node
    plan: free
    rootDir: ./
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
